// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bvyzihlgzedsllftyhhr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ2eXppaGxnemVkc2xsZnR5aGhyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwMDU3MDYsImV4cCI6MjA2OTU4MTcwNn0.IQBGN5RT8GobGoG3syUVrAHfRTk9FMeKj7yZ8fszu0s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});